---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bigbang
  namespace: flux-example
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
    namespace: flux-example
  path: ./k8s/components/bigbang/configs
  prune: true
