---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 5m
  url: https://repo1.dso.mil/big-bang/bigbang.git
  ref:
    branch: master
