apiVersion: v1
kind: Secret
metadata:
    name: registry1-creds
    namespace: bigbang
stringData:
    values.yaml: ENC[AES256_GCM,data:rMFuQCyfA+MOAB8FkLkCPtXfTHQGfxhDMCsD10zuMsB0BUCUdaDoqllKTgQLKL4a2opnoQxvSh0uuIKbi/OiIbl+7xQmDQ7UZZ6g2ZaLfrK1y4suu/hOvGE5LuAgKg==,iv:xoOUO+K2fYMwYb+kwSbHep56I6YvKHdA6DmNGwdmc1Y=,tag:GJsB/t1MywcysBBjnAXnig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9lagvkjsyf54hwat98037xr0r2v8wkavx4920px5eqwg9cx5pws5f7776
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbnhDNDRBZ3Rmc1h1STFW
            VTVSaER6OGs0UmNBdzJsaFN1cVZ3KzYwVXdnClE1Wi9MUGNNRnU1V0Ruc21oTkhz
            dUFLLzFFVUF2L0REU1FBM2lLbjFub00KLS0tIG5wbVVVSWZJRjRKa08rUTVwMDBz
            bE5sQk5rMDAyNjJaTldvWXptQmhudjgK+tsrfbhZkVHE7GSo73SSuP8NnKvFqMuz
            93lgzL/0UbzJPwTA7URooOfRj4Tza+8BmoISnn3uAlFiPFuUCw5YZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T03:13:38Z"
    mac: ENC[AES256_GCM,data:EIkmFdjrVriBnvvSlrQ/E+7xbAUSXhh+PIvmdXAjXp8obDEejrsuVaOzYeoCdx9ZK6OKSm7Yx/xu+s+z83vl01mo88y9TmiB5IQJc5pe1kfAfjupYGuJ50z2RqJjzDPxw+x75CncQZS0WUkpm1j7EXXxz90uF9mkebJJR/tUUxM=,iv:QWbuwt9oiL6Ve1es7QbAhQG7lPJ5iSuPCJlKA6o/I0c=,tag:b0yyx7Spb0ZButS060oD/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
