---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: environment-repo
  namespace: flux-example
spec:
  interval: 10m
  url: https://github.com/ryansalcido/flux-example.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: environment
  namespace: flux-example
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
    namespace: flux-example
  path: ./k8s/base
  prune: true
