---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bigbang-core-secrets
  namespace: flux-example
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./k8s/envs/dev/secrets/core
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
