apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/bigbang

secretGenerator:
  - name: registry1-creds-enc
    namespace: flux-example
    behavior: create
    files:
      - values.yaml=registry1-creds-enc.yaml
