apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bigbang.yaml

components:
  - ../../components/bigbang

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: bigbang
      namespace: bigbang
    spec:
      ref:
        tag: 1.53.0
