apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/bigbang

secretGenerator:
  - name: registry1-creds-enc
    namespace: bigbang
    behavior: create
    files:
      - values.yaml=registry1-creds-enc.yaml

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: bigbang
      namespace: bigbang
    spec:
      ref:
        tag: 1.53.0
