apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: environment-repo
      namespace: flux-example
    spec:
      ref:
        branch: main
  - |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: environment
      namespace: flux-example
    spec:
      interval: 1m
      path: ./k8s/envs/dev
