apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-values
  namespace: bigbang
data:
  values.yaml: |-
    istio:
      enabled: true
      ingressGateways:
        istio-ingressgateway:
          type: "NodePort"
          kubernetesResourceSpec:
            resources:
              limits:
                cpu: 1500m
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 1Gi
            service:
              ports:
                - name: status-port
                  port: 15021
                  targetPort: 15021
                - name: http2
                  nodePort: 30080
                  port: 80
                  targetPort: 8080
                - name: https
                  nodePort: 30443
                  port: 443
                  targetPort: 8443
                - name: tls-kafka
                  nodePort: 30092
                  port: 9092
                  targetPort: 9092

        # Disable unnecessary public IGW
        public-ingressgateway: null
      gateways:
        main:
          ingressGateway: "istio-ingressgateway"
          hosts:
            - "*.dev.cbc2.mil"

        # Disable unnecessary gateway
        public: null
